//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiMedic.Utilities.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApiMedicMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiMedicMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ApiMedic.Utilities.Resources.ApiMedicMessages", typeof(ApiMedicMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment does not exists.
        /// </summary>
        public static string AppointmentDoesNotExists {
            get {
                return ResourceManager.GetString("AppointmentDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding appointment.
        /// </summary>
        public static string ErrorAddingAppointment {
            get {
                return ResourceManager.GetString("ErrorAddingAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error canceling appointment.
        /// </summary>
        public static string ErrorCancelingAppointment {
            get {
                return ResourceManager.GetString("ErrorCancelingAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error doctor does not exists.
        /// </summary>
        public static string ErrorDoctorDoesNotExists {
            get {
                return ResourceManager.GetString("ErrorDoctorDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Doctor with appointment in same date.
        /// </summary>
        public static string ErrorDoctorWithAppointmentSameDate {
            get {
                return ResourceManager.GetString("ErrorDoctorWithAppointmentSameDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Format Date.
        /// </summary>
        public static string ErrorFormatDate {
            get {
                return ResourceManager.GetString("ErrorFormatDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting appointment.
        /// </summary>
        public static string ErrorGettingAppointment {
            get {
                return ResourceManager.GetString("ErrorGettingAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting appointments.
        /// </summary>
        public static string ErrorGettingAppointments {
            get {
                return ResourceManager.GetString("ErrorGettingAppointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting assigned time by doctor.
        /// </summary>
        public static string ErrorGettingAssignedTimeByDoctor {
            get {
                return ResourceManager.GetString("ErrorGettingAssignedTimeByDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting available times doctor.
        /// </summary>
        public static string ErrorGettingAvailableTimesDoctor {
            get {
                return ResourceManager.GetString("ErrorGettingAvailableTimesDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error No Data.
        /// </summary>
        public static string ErrorNoData {
            get {
                return ResourceManager.GetString("ErrorNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error patient does not exists.
        /// </summary>
        public static string ErrorPatientDoesNotExists {
            get {
                return ResourceManager.GetString("ErrorPatientDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating appointment.
        /// </summary>
        public static string ErrorUpdatingAppointment {
            get {
                return ResourceManager.GetString("ErrorUpdatingAppointment", resourceCulture);
            }
        }
    }
}
